2022-07-11 11:54:51,471 INFO    MainThread:106493 [internal.py:wandb_internal():90] W&B internal server running at pid: 106493, started at: 2022-07-11 11:54:51.471498
2022-07-11 11:54:51,472 INFO    WriterThread:106493 [datastore.py:open_for_write():75] open: /home/q123/Desktop/explo/wandb/run-20220711_115450-3ngu7ysb/run-3ngu7ysb.wandb
2022-07-11 11:54:51,473 DEBUG   SenderThread:106493 [sender.py:send():236] send: header
2022-07-11 11:54:51,473 DEBUG   SenderThread:106493 [sender.py:send():236] send: run
2022-07-11 11:54:52,184 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: check_version
2022-07-11 11:54:52,192 INFO    SenderThread:106493 [dir_watcher.py:__init__():216] watching files in: /home/q123/Desktop/explo/wandb/run-20220711_115450-3ngu7ysb/files
2022-07-11 11:54:52,192 INFO    SenderThread:106493 [sender.py:_start_run_threads():815] run started: 3ngu7ysb with start time 1657533290
2022-07-11 11:54:52,192 DEBUG   SenderThread:106493 [sender.py:send():236] send: summary
2022-07-11 11:54:52,192 INFO    SenderThread:106493 [sender.py:_save_file():952] saving file wandb-summary.json with policy end
2022-07-11 11:54:52,193 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: check_version
2022-07-11 11:54:52,710 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: run_start
2022-07-11 11:54:52,711 DEBUG   HandlerThread:106493 [meta.py:__init__():35] meta init
2022-07-11 11:54:52,712 DEBUG   HandlerThread:106493 [meta.py:__init__():49] meta init done
2022-07-11 11:54:52,712 DEBUG   HandlerThread:106493 [meta.py:probe():209] probe
2022-07-11 11:54:52,713 DEBUG   HandlerThread:106493 [meta.py:_setup_git():199] setup git
2022-07-11 11:54:52,727 DEBUG   HandlerThread:106493 [meta.py:_setup_git():206] setup git done
2022-07-11 11:54:52,727 DEBUG   HandlerThread:106493 [meta.py:_save_pip():53] save pip
2022-07-11 11:54:52,727 DEBUG   HandlerThread:106493 [meta.py:_save_pip():67] save pip done
2022-07-11 11:54:52,727 DEBUG   HandlerThread:106493 [meta.py:_save_conda():74] save conda
2022-07-11 11:54:52,762 DEBUG   HandlerThread:106493 [meta.py:_save_conda():84] save conda done
2022-07-11 11:54:52,762 DEBUG   HandlerThread:106493 [meta.py:probe():247] probe done
2022-07-11 11:54:52,765 DEBUG   SenderThread:106493 [sender.py:send():236] send: files
2022-07-11 11:54:52,765 INFO    SenderThread:106493 [sender.py:_save_file():952] saving file wandb-metadata.json with policy now
2022-07-11 11:54:52,773 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:54:52,773 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:54:52,813 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: partial_history
2022-07-11 11:54:53,193 INFO    Thread-7  :106493 [dir_watcher.py:_on_file_created():269] file/dir created: /home/q123/Desktop/explo/wandb/run-20220711_115450-3ngu7ysb/files/conda-environment.yaml
2022-07-11 11:54:53,193 INFO    Thread-7  :106493 [dir_watcher.py:_on_file_created():269] file/dir created: /home/q123/Desktop/explo/wandb/run-20220711_115450-3ngu7ysb/files/wandb-metadata.json
2022-07-11 11:54:53,194 INFO    Thread-7  :106493 [dir_watcher.py:_on_file_created():269] file/dir created: /home/q123/Desktop/explo/wandb/run-20220711_115450-3ngu7ysb/files/wandb-summary.json
2022-07-11 11:54:53,194 INFO    Thread-7  :106493 [dir_watcher.py:_on_file_created():269] file/dir created: /home/q123/Desktop/explo/wandb/run-20220711_115450-3ngu7ysb/files/output.log
2022-07-11 11:54:53,194 INFO    Thread-7  :106493 [dir_watcher.py:_on_file_created():269] file/dir created: /home/q123/Desktop/explo/wandb/run-20220711_115450-3ngu7ysb/files/requirements.txt
2022-07-11 11:54:53,243 DEBUG   SenderThread:106493 [sender.py:send():236] send: telemetry
2022-07-11 11:54:53,243 DEBUG   SenderThread:106493 [sender.py:send():236] send: history
2022-07-11 11:54:53,243 DEBUG   SenderThread:106493 [sender.py:send():236] send: summary
2022-07-11 11:54:53,243 INFO    SenderThread:106493 [sender.py:_save_file():952] saving file wandb-summary.json with policy end
2022-07-11 11:54:53,288 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: pause
2022-07-11 11:54:53,288 INFO    HandlerThread:106493 [handler.py:handle_request_pause():695] stopping system metrics thread
2022-07-11 11:54:53,321 DEBUG   SenderThread:106493 [sender.py:send():236] send: stats
2022-07-11 11:54:53,817 INFO    Thread-11 :106493 [upload_job.py:push():138] Uploaded file /tmp/tmpbikuufydwandb/1dbab1oa-wandb-metadata.json
2022-07-11 11:54:54,193 INFO    Thread-7  :106493 [dir_watcher.py:_on_file_modified():286] file/dir modified: /home/q123/Desktop/explo/wandb/run-20220711_115450-3ngu7ysb/files/wandb-summary.json
2022-07-11 11:54:55,193 INFO    Thread-7  :106493 [dir_watcher.py:_on_file_modified():286] file/dir modified: /home/q123/Desktop/explo/wandb/run-20220711_115450-3ngu7ysb/files/output.log
2022-07-11 11:55:08,249 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:55:08,249 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:55:23,206 INFO    Thread-7  :106493 [dir_watcher.py:_on_file_modified():286] file/dir modified: /home/q123/Desktop/explo/wandb/run-20220711_115450-3ngu7ysb/files/config.yaml
2022-07-11 11:55:23,674 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:55:23,674 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:55:39,157 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:55:39,158 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:55:54,695 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:55:54,696 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:56:14,695 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:56:14,695 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:56:30,226 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:56:30,227 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:56:45,688 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:56:45,689 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:57:01,433 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:57:01,433 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:57:09,013 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: resume
2022-07-11 11:57:09,013 INFO    HandlerThread:106493 [handler.py:handle_request_resume():686] starting system metrics thread
2022-07-11 11:57:09,036 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: pause
2022-07-11 11:57:09,036 INFO    HandlerThread:106493 [handler.py:handle_request_pause():695] stopping system metrics thread
2022-07-11 11:57:09,116 DEBUG   SenderThread:106493 [sender.py:send():236] send: stats
2022-07-11 11:57:14,869 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: resume
2022-07-11 11:57:14,869 INFO    HandlerThread:106493 [handler.py:handle_request_resume():686] starting system metrics thread
2022-07-11 11:57:14,930 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: pause
2022-07-11 11:57:14,930 INFO    HandlerThread:106493 [handler.py:handle_request_pause():695] stopping system metrics thread
2022-07-11 11:57:14,971 DEBUG   SenderThread:106493 [sender.py:send():236] send: stats
2022-07-11 11:57:16,920 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:57:16,921 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:57:32,397 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:57:32,397 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:57:47,846 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:57:47,847 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:58:07,394 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:58:07,394 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:58:25,957 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:58:25,957 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:58:41,432 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:58:41,432 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:58:56,964 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:58:56,965 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:59:12,596 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:59:12,597 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:59:32,597 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:59:32,597 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 11:59:48,426 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 11:59:48,427 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 12:00:05,482 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:00:05,482 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 12:00:25,482 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:00:25,482 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 12:00:45,021 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:00:45,021 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 12:01:05,021 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:01:05,022 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 12:01:21,091 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:01:21,092 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 12:01:41,092 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:01:41,092 DEBUG   SenderThread:106493 [sender.py:send_request():250] send_request: stop_status
2022-07-11 12:01:52,933 ERROR   SenderThread:106493 [retry.py:__call__():132] Retry attempt failed:
Traceback (most recent call last):
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fba281a3a60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba281a3a60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 108, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 158, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba281a3a60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-07-11 12:01:55,379 INFO    Thread-7  :106493 [dir_watcher.py:_on_file_modified():286] file/dir modified: /home/q123/Desktop/explo/wandb/run-20220711_115450-3ngu7ysb/files/output.log
2022-07-11 12:02:01,093 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:02:21,093 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:02:41,094 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:03:01,095 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:03:21,095 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:03:41,096 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:04:01,096 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:04:21,097 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:04:41,098 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:05:01,098 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:05:21,098 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:05:41,099 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:06:01,100 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:06:21,100 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:06:41,101 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:07:01,102 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:07:21,102 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:07:41,103 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:08:01,104 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:08:21,104 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:08:41,105 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:09:01,105 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:09:21,106 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:09:41,107 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:10:01,107 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:10:21,108 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:10:41,109 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:11:01,109 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:11:21,110 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:11:41,110 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:12:01,111 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:12:21,111 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:12:41,112 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:13:01,113 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:13:21,113 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:13:41,114 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:14:01,114 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:14:21,115 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:14:41,116 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:15:01,116 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:15:21,117 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:15:41,117 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:16:01,118 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:16:21,118 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:16:41,119 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:17:01,120 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:17:21,120 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:17:41,121 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:18:01,122 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:18:21,122 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:18:41,123 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:19:01,124 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:19:21,124 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:19:41,125 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:20:01,126 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:20:21,126 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:20:41,127 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:21:01,128 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:21:21,128 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:21:41,129 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:22:01,130 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:22:21,130 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:22:41,131 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:23:01,131 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:23:21,132 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:23:41,133 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:24:01,133 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:24:21,134 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:24:41,135 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:25:01,135 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:25:21,136 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:25:41,137 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:26:01,137 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:26:21,138 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:26:41,138 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:27:01,139 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:27:21,140 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:27:41,140 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:28:01,141 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:28:21,142 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:28:41,142 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:29:01,143 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:29:21,144 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:29:41,144 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:29:55,114 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 12:30:01,145 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:30:12,306 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba06f5bac0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 12:30:21,146 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:30:26,973 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba06f597e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 12:30:41,146 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:30:45,557 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba06f5bac0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 12:31:01,147 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:31:15,403 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba06f5b9d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 12:31:21,147 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:31:41,148 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:31:57,750 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba06f59e10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 12:32:01,149 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:32:21,150 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:32:41,150 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:33:01,151 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:33:14,573 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba06f5b6a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 12:33:21,151 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:33:41,152 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:34:01,153 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:34:21,154 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:34:41,154 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:35:01,155 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:35:21,155 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:35:41,156 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:35:55,797 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba06f59570>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 12:36:01,157 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:36:21,157 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:36:41,158 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:37:01,159 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:37:21,159 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:37:41,160 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:38:01,160 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:38:21,161 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:38:41,162 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:39:01,162 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:39:21,163 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:39:41,163 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:40:01,164 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:40:21,165 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:40:41,165 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:41:01,166 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:41:08,398 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba281a3c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 12:41:21,167 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:41:41,167 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:42:01,168 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:42:21,168 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:42:41,169 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:43:01,170 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:43:21,170 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:43:41,171 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:44:01,171 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:44:21,172 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:44:41,173 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:45:01,174 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:45:21,174 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:45:41,175 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:46:01,175 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:46:21,176 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:46:41,177 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:47:01,177 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:47:21,178 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:47:31,425 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba06f5b190>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 12:47:41,179 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:48:01,179 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:48:21,180 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:48:41,180 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:49:01,181 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:49:21,182 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:49:41,182 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:50:01,183 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:50:21,184 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:50:41,184 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:51:01,185 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:51:21,186 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:51:41,186 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:52:01,187 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:52:21,187 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:52:41,188 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:52:43,798 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba06f59690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 12:53:01,188 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:53:21,189 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:53:41,190 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:54:01,190 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:54:21,191 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:54:41,192 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:55:01,192 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:55:21,193 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:55:41,194 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:56:01,194 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:56:21,195 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:56:41,195 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:57:01,196 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:57:21,196 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:57:41,197 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:58:01,198 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:58:20,004 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba281a3cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 12:58:21,198 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:58:41,199 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:59:01,200 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:59:21,200 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 12:59:41,201 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:00:01,202 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:00:21,202 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:00:41,203 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:01:01,203 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:01:21,204 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:01:41,205 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:02:01,205 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:02:21,206 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:02:41,207 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:03:01,207 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:03:21,208 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:03:41,209 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:04:01,209 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:04:10,136 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba281a38e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 13:04:21,210 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:04:41,211 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:05:01,211 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:05:21,212 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:05:41,213 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:06:01,213 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:06:21,214 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:06:41,215 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:07:01,215 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:07:21,216 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:07:41,217 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:08:01,217 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:08:21,218 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:08:41,219 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:09:01,219 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:09:21,220 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:09:35,912 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba06f5b580>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 13:09:41,221 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:10:01,221 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:10:21,222 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:10:41,222 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:11:01,223 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:11:21,224 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:11:41,224 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:12:01,225 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:12:21,226 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:12:41,226 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:13:01,227 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:13:21,228 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:13:41,228 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:14:01,229 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:14:21,230 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:14:41,230 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:15:01,231 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:15:21,231 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:15:40,565 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba06f59030>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 13:15:41,232 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:16:01,233 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:16:21,233 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:16:41,234 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:17:01,235 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:17:21,235 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:17:41,236 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:18:01,236 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:18:21,237 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:18:41,237 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:19:01,238 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:19:21,239 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:19:41,239 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:20:01,240 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:20:21,240 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:20:41,241 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:21:01,242 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:21:04,987 WARNING FileStreamThread:106493 [file_stream.py:request_with_retry():589] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mahdikallel/explo/3ngu7ysb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba06f5a200>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fba28109420>>, args: ('https://api.wandb.ai/files/mahdikallel/explo/3ngu7ysb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-07-11 13:21:21,242 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:21:41,243 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:22:01,244 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:22:21,244 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:22:41,245 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:23:01,245 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:23:21,246 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:23:41,246 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:24:01,247 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:24:21,248 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:24:41,248 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:25:01,249 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:25:21,250 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:25:41,250 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:26:01,251 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:26:21,251 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:26:41,252 DEBUG   HandlerThread:106493 [handler.py:handle_request():140] handle_request: stop_status
2022-07-11 13:26:55,296 WARNING MainThread:106493 [internal.py:wandb_internal():153] Internal process interrupt: 1
